- name: Ensure tmp folder exists
  file: path=/tmp/wp_repos_zip state=directory mode=0755

- name: Copy w3tc_admin_url.patch to tmp folder
  copy: src=w3tc_admin_url.patch dest=/tmp/w3tc_admin_url.patch owner=www-data group=www-data mode=0755

- name: apply patch to w3tc
  shell: patch < w3tc_admin_url.patch -d /var/www/html/wp-content/plugins/w3-total-cache
  args:
    chdir: /tmp/
  
- name: Clear /cache folder
  shell: rm -rf /cache/*
  
- name: Clear /tmp/wp_repos_zip
  shell: rm -rf /tmp/wp_repos_zip/*