- name: Download composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 force=yes validate_certs=False

- name: Install node, npm and bower
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - ; sudo apt-get install -y nodejs; sudo install npm; sudo npm install bower -g

- name: Ensure tmp folder exists
  file: path=/tmp/wp_repos_zip state=directory mode=0755

- name: Install required packages.
  action: apt pkg={{ item }} state=present
  sudo: yes
  with_items:
    - gettext
    - unzip
