- name: Install composer
  shell: wget -O /usr/local/bin/composer https://getcomposer.org/composer.phar

- name: Install node, npm and bower
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - ; sudo apt-get install -y nodejs; sudo install npm; sudo npm install bower -g
