- name: Updating ckan components
  shell: pip install --upgrade git+{{ item.url }}.git@{{ item.branch }}#egg={{ item.name }}
  with_items: ckan_repos

- name: Restarting ckan
  shell: touch /run/uwsgi-reload
