- name: Updating ckan components
  shell: pip install --upgrade git+{{ item.url }}.git@{{ item.branch }}#egg={{ item.name }}
  with_items: "{{ ckan_repos }}"
  sudo: yes

- name: Ensure there are no duplicates
  shell: msguniq --unique {{ckan_path}}i18n/{{item.origin}}/LC_MESSAGES/ckan.po -o {{ckan_path}}i18n/{{item.origin}}/LC_MESSAGES/ckan.po
  with_items: "{{ langs }}"

- name: Update CKAN translations ( Merge .po files)
  shell: msgcat --use-first {{ckan_path}}i18n/{{item.origin}}/LC_MESSAGES/ckan.po /usr/local/lib/python2.7/dist-packages/ckanext/odm_dataset/i18n/{{item.origin}}.po /usr/local/lib/python2.7/dist-packages/ckanext/odm_library/i18n/{{item.origin}}.po /usr/local/lib/python2.7/dist-packages/ckanext/odm_laws/i18n/{{item.origin}}.po /usr/local/lib/python2.7/dist-packages/ckanext/odm_migration/i18n/{{item.origin}}.po /usr/local/lib/python2.7/dist-packages/ckanext/odm_audit/i18n/{{item.origin}}.po /usr/local/lib/python2.7/dist-packages/ckanext/odm_nav/i18n/{{item.origin}}.po /usr/local/lib/python2.7/dist-packages/ckanext/issues/i18n/{{item.origin}}.po -o {{ckan_path}}i18n/{{item.origin}}/LC_MESSAGES/ckan.po
  with_items: "{{ langs }}"

- name: Update CKAN translations ( Compile .mo file)
  shell: msgfmt -o {{ckan_path}}i18n/{{item.dest}}/LC_MESSAGES/ckan.mo {{ckan_path}}i18n/{{item.dest}}/LC_MESSAGES/ckan.po
  with_items: "{{ langs }}"

- name: Restarting ckan
  shell: touch /run/uwsgi-reload
  sudo: yes
