- name: Update Wordpress components using git
  shell: git clean -f; git reset --hard HEAD; git checkout {{item.branch}}; git pull origin {{item.branch}} ;git submodule init; git submodule update; git checkout {{item.branch}};
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"

- name: Ensure tmp folder exists
  file: path=/tmp/wp_repos_zip state=directory mode=0755

- name: Download plugins as ZIP files
  get_url: url={{ item.downloadable }}  dest=/tmp/wp_repos_zip/{{ item.installable }} mode=0755
  with_items: "{{ wp_repos_zip }}"

- name: Update Wordpress components using zip files
  shell: unzip -o /tmp/wp_repos_zip/{{ item.installable }} -d ./
  with_items: "{{ wp_repos_zip }}"
  args:
    chdir: "{{ item.path }}"

- name: Install composer dependencies
  shell: rm -rf vendor; composer update;
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.composer_deps
  become: yes
  become_user: root
  become_method: sudo

- name: Install bower dependencies
  shell: bower install --allow-root;
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.bower_deps
  become: yes
  become_user: root
  become_method: sudo

- name: Install npm dependencies
  shell: sudo npm install; node node_modules/bower/bin/bower install --allow-root; node node_modules/gulp/bin/gulp.js
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.npm_deps

- name: Run gulp tasks
  shell: gulp
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.run_gulp

- name: Ensure there are no duplicates - jeo
  shell: msguniq --unique /var/www/html/wp-content/themes/jeo/i18n/{{item.origin}}.po -o /var/www/html/wp-content/themes/jeo/i18n/{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wp-odm_theme
  shell: msguniq --unique /var/www/html/wp-content/themes/wp-odm_theme/i18n/wp-odm_theme-{{item.origin}}.po -o /var/www/html/wp-content/themes/wp-odm_theme/i18n/wp-odm_theme-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - profiles
  shell: msguniq --unique /var/www/html/wp-content/plugins/wp-odm_profile_pages/i18n/wp-odm_profile_pages-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wp-odm_profile_pages/i18n/wp-odm_profile_pages-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - tabular
  shell: msguniq --unique /var/www/html/wp-content/plugins/wp-odm_tabular_pages/i18n/wp-odm_tabular_pages-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wp-odm_tabular_pages/i18n/wp-odm_tabular_pages-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wpckan
  shell: msguniq --unique /var/www/html/wp-content/plugins/wpckan/i18n/wpckan-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wpckan/i18n/wpckan-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wpsparql
  shell: msguniq --unique /var/www/html/wp-content/plugins/wpsparql/i18n/wpsparql-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wpsparql/i18n/wpsparql-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wp-odm_user_feedback
  shell: msguniq --unique /var/www/html/wp-content/plugins/wp-odm_user_feedback/i18n/wp-odm_user_feedback-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wp-odm_user_feedback/i18n/wp-odm_user_feedback-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wp-odm_dash
  shell: msguniq --unique /var/www/html/wp-content/plugins/wp-odm_dash/i18n/wp-odm_dash-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wp-odm_dash/i18n/wp-odm_dash-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wp-odm_related
  shell: msguniq --unique /var/www/html/wp-content/plugins/wp-odm_related/i18n/wp-odm_related-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wp-odm_related/i18n/wp-odm_related-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Ensure there are no duplicates - wp-odm_solr
  shell: msguniq --unique /var/www/html/wp-content/plugins/wp-odm_solr/i18n/wp-odm_solr-{{item.origin}}.po -o /var/www/html/wp-content/plugins/wp-odm_solr/i18n/wp-odm_solr-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: copy all .po files to /var/www/html/wp-content/languages/ recursively
  shell: find /var/www/html/wp-content/ -type f -name '*.po' -exec cp {} /var/www/html/wp-content/languages/{} \;

- name: merge all .po files into a single one
  shell: msgcat *{{item.origin}}.po -o odi.po
  with_items: "{{langs}}"
  args:
    chdir: /var/www/html/wp-content/languages/

- name: Compile odi.mo file for each language
  shell: msgfmt -o odi-{{item.origin}}.mo odi-{{item.origin}}.po
  with_items: "{{ langs }}"
  args:
    chdir: /var/www/html/wp-content/languages/

- name: Set user and group for all files in plugins
  file: path=/var/www/html/wp-content/plugins owner=www-data group=www-data recurse=yes

- name: Set user and group for all files in themes
  file: path=/var/www/html/wp-content/themes owner=www-data group=www-data recurse=yes

- name: Copy tinymce.min.js file to hack the wordpress editor so it does not trim
  copy: src=tinymce.min.js dest=/var/www/html/wp-includes/js/tinymce/tinymce.min.js owner=www-data group=www-data
