- name: Update Wordpress components using git
  shell: git clean -d -ff; git reset --hard HEAD; git checkout {{item.branch}}; git pull origin {{item.branch}} ;git submodule init; git submodule update
  args:
    chdir: "{{ item.path }}"
  with_items: wp_repos
