- name: Update Wordpress components using git
  shell: git clean -f; git reset --hard HEAD; git checkout {{item.branch}}; git pull origin {{item.branch}} ;git submodule init; git submodule update; git checkout {{item.branch}};
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"

- name: Ensure tmp folder exists
  file: path=/tmp/wp_repos_zip state=directory mode=0755

- name: Download plugins as ZIP files
  get_url: url={{ item.downloadable }}  dest=/tmp/wp_repos_zip/{{ item.installable }} mode=0755
  with_items: "{{ wp_repos_zip }}"

- name: Update Wordpress components using zip files
  unarchive: src=/tmp/wp_repos_zip/{{ item.installable }} copy=no dest={{ item.path }} owner=www-data group=www-data
  with_items: "{{ wp_repos_zip }}"

- name: Install composer dependencies
  shell: composer update;
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.composer_deps
  become: yes
  become_user: root
  become_method: sudo

- name: Install bower dependencies
  shell: bower install --allow-root;
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.bower_deps
  become: yes
  become_user: root
  become_method: sudo

- name: Install npm dependencies
  shell: sudo npm install; node node_modules/bower/bin/bower install --allow-root; node node_modules/gulp/bin/gulp.js
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.npm_deps

- name: Run gulp tasks
  shell: gulp
  args:
    chdir: "{{ item.path }}"
  with_items: "{{ wp_repos }}"
  when: item.run_gulp

- name: Update Wordpress translations ( Merge .po files) - themes
  shell: msgcat /var/www/html/wp-content/themes/jeo/i18n/{{item.origin}}.po /var/www/html/wp-content/themes/wp-odm_theme/i18n/{{item.origin}}.po -o /var/www/html/wp-content/languages/{{item.dest}}.po
  with_items: "{{ langs }}"

- name: Update Wordpress translations ( Compile .mo file) - themes
  shell: msgfmt -o /var/www/html/wp-content/languages/{{item.dest}}.mo /var/www/html/wp-content/languages/{{item.dest}}.po
  with_items: "{{ langs }}"

- name: Update Wordpress translations ( Compile .mo file) - profiles
  shell: msgfmt -o /var/www/html/wp-content/plugins/wp-odm_profile_pages/i18n/wp-odm_profile_pages-{{item.origin}}.mo /var/www/html/wp-content/plugins/wp-odm_profile_pages/i18n/wp-odm_profile_pages-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Update Wordpress translations ( Compile .mo file) - tabular
  shell: msgfmt -o /var/www/html/wp-content/plugins/wp-odm_tabular_pages/i18n/wp-odm_tabular_pages-{{item.origin}}.mo /var/www/html/wp-content/plugins/wp-odm_tabular_pages/i18n/wp-odm_tabular_pages-{{item.origin}}.po
  with_items: "{{ langs }}"
  
- name: Update Wordpress translations ( Compile .mo file) - wpckan
  shell: msgfmt -o /var/www/html/wp-content/plugins/wpckan/i18n/wpckan-{{item.origin}}.mo /var/www/html/wp-content/plugins/wpckan/i18n/wpckan-{{item.origin}}.po
  with_items: "{{ langs }}"

- name: Set user and group for all files in plugins
  file: path=/var/www/html/wp-content/plugins owner=www-data group=www-data recurse=yes

- name: Set user and group for all files in themes
  file: path=/var/www/html/wp-content/themes owner=www-data group=www-data recurse=yes

- name: Copy tinymce.min.js file to hack the wordpress editor so it does not trim
  copy: src=tinymce.min.js dest=/var/www/html/wp-includes/js/tinymce/tinymce.min.js owner=www-data group=www-data
