- name: Update Wordpress components using git
  shell: git clean -f; git reset --hard HEAD; git checkout {{item.branch}}; git pull origin {{item.branch}} ;git submodule init; git submodule update; git checkout {{item.branch}};
  args:
    chdir: "{{ item.path }}"
  with_items: wp_repos

- name: Update Wordpress components using zip files
  unarchive: src={{ item.installable }} dest={{ item.path }} remote_src=no owner=www-data group=www-data
  with_items: wp_repos_zip

- name: Install composer dependencies
  shell: composer update;
  args:
    chdir: "{{ item.path }}"
  with_items: wp_repos
  when: item.composer_deps
  sudo: yes

- name: Install bower dependencies
  shell: bower install --allow-root;
  args:
    chdir: "{{ item.path }}"
  with_items: wp_repos
  when: item.bower_deps
  sudo: yes

- name: Install npm dependencies
  shell: sudo npm install; node node_modules/bower/bin/bower install --allow-root; node node_modules/gulp/bin/gulp.js
  args:
    chdir: "{{ item.path }}"
  with_items: wp_repos
  when: item.npm_deps

- name: Update Wordpress translations ( Merge .po files)
  shell: msgcat /var/www/html/wp-content/themes/jeo/i18n/{{item.origin}}.po /var/www/html/wp-content/themes/wp-odm_theme/i18n/{{item.origin}}.po -o /var/www/html/wp-content/languages/{{item.dest}}.po
  with_items: langs

- name: Update Wordpress translations ( Compile .mo file)
  shell: msgfmt -o /var/www/html/wp-content/languages/{{item.dest}}.mo /var/www/html/wp-content/languages/{{item.dest}}.po
  with_items: langs

- name: Set user and group for all files
  file: path=/var/www/html/ owner=www-data group=www-data recurse=yes
